---

- import_tasks: "{{ role_path }}/tasks/setup_synapse_pre.yml"

- import_tasks: "{{ role_path }}/tasks/ext/setup.yml"

- import_tasks: "{{ role_path }}/tasks/setup_synapse_main.yml"

- import_tasks: "{{ role_path }}/tasks/setup_synapse_goofys.yml"
