---

- import_tasks: "{{ role_path }}/tasks/ext/rest-auth/setup.yml"

- import_tasks: "{{ role_path }}/tasks/ext/shared-secret-auth/setup.yml"

- import_tasks: "{{ role_path }}/tasks/ext/ldap-auth/setup.yml"

- import_tasks: "{{ role_path }}/tasks/ext/mautrix-telegram/setup.yml"

- import_tasks: "{{ role_path }}/tasks/ext/mautrix-whatsapp/setup.yml"

- import_tasks: "{{ role_path }}/tasks/ext/appservice-irc/setup.yml"

- import_tasks: "{{ role_path }}/tasks/ext/appservice-discord/setup.yml"
