- import_tasks: "{{ role_path }}/tasks/init.yml"
  tags:
    - always

- import_tasks: "{{ role_path }}/tasks/validate_config.yml"
  when: "run_setup and matrix_corporal_enabled"
  tags:
    - setup-all
    - setup-corporal

- import_tasks: "{{ role_path }}/tasks/setup_corporal.yml"
  when: run_setup
  tags:
    - setup-all
    - setup-corporal

- import_tasks: "{{ role_path }}/tasks/self_check_corporal.yml"
  delegate_to: 127.0.0.1
  become: false
  when: "run_self_check and matrix_corporal_enabled"
  tags:
    - self-check