---

- name: Fail if required matrix-corporal settings not defined
  fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`) for using matrix-corporal.
  when: "vars[item] == ''"
  with_items:
    - "matrix_corporal_matrix_homeserver_api_endpoint"
    - "matrix_corporal_matrix_auth_shared_secret"
    - "matrix_corporal_matrix_registration_shared_secret"
    - "matrix_corporal_policy_provider_config"

- name: Fail if HTTP API enabled, but no token set
  fail:
    msg: "The Matrix Corporal HTTP API is enabled (`matrix_corporal_http_api_enabled`), but no auth token has been set in `matrix_corporal_http_api_auth_token`"
  when: "matrix_corporal_http_api_enabled and matrix_corporal_http_api_auth_token == ''"
