---

#
# Tasks related to setting up matrix-synapse-shared-secret-auth
#

- name: Fail if Shared Secret Auth enabled, but no secret set
  fail:
    msg: "Shared Secret Auth is enabled, but no secret has been set in matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret"
  when: "matrix_synapse_ext_password_provider_shared_secret_auth_enabled and matrix_synapse_ext_password_provider_shared_secret_auth_shared_secret == ''"

- name: Download matrix-synapse-shared-secret-auth
  get_url:
    url: "{{ matrix_synapse_ext_password_provider_shared_secret_auth_download_url }}"
    dest: "{{ matrix_synapse_ext_path }}/shared_secret_authenticator.py"
    force: true
    mode: 0440
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_username }}"
  when: "matrix_synapse_ext_password_provider_shared_secret_auth_enabled"

- set_fact:
    matrix_synapse_password_providers_enabled: true
  when: "matrix_synapse_ext_password_provider_shared_secret_auth_enabled"

- set_fact:
    matrix_synapse_container_additional_volumes: >
      {{ matrix_synapse_container_additional_volumes }}
      +
      {{ [{'src': '{{ matrix_synapse_ext_path }}/shared_secret_authenticator.py', 'dst': '{{ matrix_synapse_in_container_python_packages_path }}/shared_secret_authenticator.py', 'options': 'ro'}] }}
  when: "matrix_synapse_ext_password_provider_shared_secret_auth_enabled"

- set_fact:
    matrix_synapse_additional_loggers: >
      {{ matrix_synapse_additional_loggers }}
      +
      {{ [{'name': 'shared_secret_authenticator', 'level': 'INFO'}] }}
  when: "matrix_synapse_ext_password_provider_shared_secret_auth_enabled"

#
# Tasks related to getting rid of matrix-synapse-shared-secret-auth (if it was previously enabled)
#

- name: Ensure matrix-synapse-shared-secret-auth doesn't exist
  file:
    path: "{{ matrix_synapse_ext_path }}/shared_secret_authenticator.py"
    state: absent
  when: "not matrix_synapse_ext_password_provider_shared_secret_auth_enabled"