---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "cahoots-in.fullname" . }}-secrets
  labels:
{{ include "cahoots-in.labels" . | indent 4 }}
data:
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  ngrok-token: {{ .Values.ngrok.token | b64enc | quote }}
  oauth2-client-secret: {{ .Values.oauth2.client_secret | b64enc | quote }}
