---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: digital-ocean
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: dobs.csi.digitalocean.com
reclaimPolicy: Retain
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cahoots-uploads-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: digital-ocean
