---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cahoots-uploads-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
