---

- name: Fail if required riot-web settings not defined
  fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`) for using riot-web.
  when: "vars[item] == ''"
  with_items:
    - "matrix_riot_web_default_hs_url"

- name: (Deprecation) Catch and report renamed settings
  fail:
    msg: >
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - {'old': 'matrix_riot_web_homepage_template', 'new': 'matrix_riot_web_embedded_pages_home_path'}
    - {'old': 'matrix_riot_web_homepage_template_general', 'new': '<removed>'}
    - {'old': 'matrix_riot_web_homepage_template_technical', 'new': '<removed>'}
    - {'old': 'matrix_riot_web_homepage_template_building', 'new': '<removed>'}
    - {'old': 'matrix_riot_web_homepage_template_contributing', 'new': '<removed>'}
