---

- set_fact:
    matrix_synapse_media_store_parent_path: "{{ matrix_synapse_media_store_path|dirname }}"
    matrix_synapse_media_store_directory_name: "{{ matrix_synapse_media_store_path|basename }}"

- name: Ensure Synapse paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_username }}"
  with_items:
    - "{{ matrix_synapse_config_dir_path }}"
    - "{{ matrix_synapse_run_path }}"
    - "{{ matrix_synapse_ext_path }}"
    # We handle matrix_synapse_media_store_path elsewhere (in setup_synapse_main.yml),
    # because if it's using Goofys and it's already mounted (from before),
    # trying to chown/chmod it here will cause trouble.
