name: 🚢 K8S Docker Image

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: K8S Docker Image (Kubernetes Deployment)
      uses: whoan/docker-build-with-cache-action@v5.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        image_name: gabrielfalcao/k8s-cahoots-in
        image_tag: "${{ github.sha }}"
        dockerfile: Dockerfile
